[project]
authors = [{email = "partnerships@cradle.bio", name = "Cradle"}]
description = "Examples for using custom predictors with Cradle"
name = "custom-predictor-examples"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

dependencies = [
  "cradle-sdk~=0.4.1"
]

[dependency-groups]
dev = [
    "ruff>=0.11.4",
    "pyright>=1.1.402",
    "pre-commit>=2.9.2",
]

[tool.ruff]
line-length = 120

[tool.pyright]
extraPaths = ["../uv"]
